version: "3.9"

services:
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:3.1.426-alpine3.16
    volumes:
      - ./app:/app
    working_dir: /app
    command: dotnet watch run
    ports:
      - "5000:5000"
